# Generated by Django 6.0.1 on 2026-01-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Not Playing', max_length=100)),
                ('artist', models.CharField(default='Unknown', max_length=100)),
                ('album_art', models.URLField(blank=True, default='')),
                ('is_playing', models.BooleanField(default=False)),
                ('progress', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=180)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_temp', models.IntegerField(default=22)),
                ('passenger_temp', models.IntegerField(default=22)),
                ('fan_speed', models.IntegerField(default=3)),
                ('volume', models.IntegerField(default=50)),
            ],
        ),
    ]
